application:
  version: 1.0

server:
  servlet:
    context-path: "/management"

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.jdbc.batch_size: 20
      hibernate.cache.use_query_cache: false
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_structured_entries: false
      hibernate.cache.use_minimal_puts: false
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/management
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver